[package]
name = "nonvolatile"
version = "0.1.0"
authors = ["Jacob Sacco <jacobsacco@ou.edu>"]
edition = "2018"
description = "A package providing the ability to store configuration data out of the way"
repository = "https://github.com/jacobsacco/rs_nonvolatile"
license = "MIT"
license-file = "License.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.98", features = ["derive"] }
whoami = "0.5.3"
serde_yaml = "0.8.9"
fs_util = "0.1.0"
generic_error = "0.1.0"
